const jobs = [
  {
    title: "Software Engineer",
    company: "Google",
    location: "California, USA",
    experience: "2+ years",
  },
  {
    title: "UI/UX Designer",
    company: "Amazon",
    location: "New York, USA",
    experience: "3+ years",
  },
  {
    title: "Data Scientist",
    company: "Microsoft",
    location: "Seattle, USA",
    experience: "4+ years",
  },
  {
    title: "Marketing Manager",
    company: "Tesla",
    location: "Austin, USA",
    experience: "5+ years",
  },
  {
    title: "Backend Developer",
    company: "Netflix",
    location: "San Francisco, USA",
    experience: "3+ years",
  },
  {
    title: "Cloud Engineer",
    company: "IBM",
    location: "Toronto, Canada",
    experience: "2+ years",
  },
  {
    title: "Cyber Security Analyst",
    company: "Cisco",
    location: "Boston, USA",
    experience: "3+ years",
  },
  {
    title: "Product Manager",
    company: "Apple",
    location: "Cupertino, USA",
    experience: "6+ years",
  },
  {
    title: "Machine Learning Engineer",
    company: "Facebook",
    location: "Menlo Park, USA",
    experience: "5+ years",
  },
  {
    title: "Full Stack Developer",
    company: "Adobe",
    location: "San Jose, USA",
    experience: "3+ years",
  },
  {
    title: "DevOps Engineer",
    company: "Intel",
    location: "Phoenix, USA",
    experience: "4+ years",
  },
  {
    title: "Blockchain Developer",
    company: "Coinbase",
    location: "Remote",
    experience: "3+ years",
  },
  {
    title: "Financial Analyst",
    company: "Goldman Sachs",
    location: "New York, USA",
    experience: "2+ years",
  },
  {
    title: "Investment Banker",
    company: "JP Morgan",
    location: "London, UK",
    experience: "5+ years",
  },
  {
    title: "AI Research Scientist",
    company: "OpenAI",
    location: "San Francisco, USA",
    experience: "6+ years",
  },
  {
    title: "Game Developer",
    company: "Epic Games",
    location: "Raleigh, USA",
    experience: "3+ years",
  },
  {
    title: "Front-end Developer",
    company: "Shopify",
    location: "Ottawa, Canada",
    experience: "2+ years",
  },
  {
    title: "HR Manager",
    company: "Deloitte",
    location: "Chicago, USA",
    experience: "5+ years",
  },
  {
    title: "Legal Advisor",
    company: "PwC",
    location: "Sydney, Australia",
    experience: "7+ years",
  },
  {
    title: "Graphic Designer",
    company: "Canva",
    location: "Melbourne, Australia",
    experience: "3+ years",
  },
  {
    title: "Software Architect",
    company: "Oracle",
    location: "Redwood City, USA",
    experience: "8+ years",
  },
  {
    title: "Mobile App Developer",
    company: "Spotify",
    location: "Stockholm, Sweden",
    experience: "4+ years",
  },
  {
    title: "E-commerce Manager",
    company: "eBay",
    location: "Berlin, Germany",
    experience: "5+ years",
  },
  {
    title: "Sales Manager",
    company: "Salesforce",
    location: "Denver, USA",
    experience: "6+ years",
  },
  {
    title: "Technical Support Engineer",
    company: "Dell",
    location: "Austin, USA",
    experience: "3+ years",
  },
  {
    title: "IT Project Manager",
    company: "HP",
    location: "Houston, USA",
    experience: "7+ years",
  },
  {
    title: "Digital Marketing Specialist",
    company: "HubSpot",
    location: "Boston, USA",
    experience: "4+ years",
  },
  {
    title: "SEO Specialist",
    company: "Moz",
    location: "Seattle, USA",
    experience: "3+ years",
  },
  {
    title: "Supply Chain Analyst",
    company: "FedEx",
    location: "Memphis, USA",
    experience: "5+ years",
  },
  {
    title: "Biomedical Engineer",
    company: "Medtronic",
    location: "Minneapolis, USA",
    experience: "3+ years",
  },
  {
    title: "Aerospace Engineer",
    company: "SpaceX",
    location: "Hawthorne, USA",
    experience: "6+ years",
  },
  {
    title: "Chemical Engineer",
    company: "Dow Chemicals",
    location: "Michigan, USA",
    experience: "4+ years",
  },
  {
    title: "Mechanical Engineer",
    company: "Boeing",
    location: "Chicago, USA",
    experience: "5+ years",
  },
  {
    title: "Electrical Engineer",
    company: "General Electric",
    location: "Boston, USA",
    experience: "4+ years",
  },
  {
    title: "Civil Engineer",
    company: "AECOM",
    location: "Dallas, USA",
    experience: "3+ years",
  },
  {
    title: "Architect",
    company: "Foster + Partners",
    location: "London, UK",
    experience: "6+ years",
  },
  {
    title: "Data Analyst",
    company: "LinkedIn",
    location: "Sunnyvale, USA",
    experience: "3+ years",
  },
  {
    title: "Risk Manager",
    company: "Morgan Stanley",
    location: "Hong Kong",
    experience: "7+ years",
  },
  {
    title: "Copywriter",
    company: "Ogilvy",
    location: "New York, USA",
    experience: "2+ years",
  },
  {
    title: "Content Manager",
    company: "BuzzFeed",
    location: "Los Angeles, USA",
    experience: "3+ years",
  },
  {
    title: "Business Analyst",
    company: "McKinsey & Co.",
    location: "Dubai, UAE",
    experience: "4+ years",
  },
  {
    title: "Retail Manager",
    company: "Walmart",
    location: "Bentonville, USA",
    experience: "5+ years",
  },
  {
    title: "Fashion Designer",
    company: "Gucci",
    location: "Milan, Italy",
    experience: "6+ years",
  },
  {
    title: "AI Ethics Researcher",
    company: "DeepMind",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "Medical Doctor",
    company: "Mayo Clinic",
    location: "Rochester, USA",
    experience: "10+ years",
  },
  {
    title: "Pharmacist",
    company: "Walgreens",
    location: "Chicago, USA",
    experience: "4+ years",
  },
  {
    title: "Public Relations Manager",
    company: "Coca-Cola",
    location: "Atlanta, USA",
    experience: "6+ years",
  },
  {
    title: "Event Coordinator",
    company: "Red Bull",
    location: "Vienna, Austria",
    experience: "3+ years",
  },
  {
    title: "Actuary",
    company: "AIG",
    location: "Zurich, Switzerland",
    experience: "5+ years",
  },
  {
    title: "HR Business Partner",
    company: "SAP",
    location: "Berlin, Germany",
    experience: "4+ years",
  },
  {
    title: "Cloud Security Engineer",
    company: "AWS",
    location: "Seattle, USA",
    experience: "5+ years",
  },
  {
    title: "Robotics Engineer",
    company: "Boston Dynamics",
    location: "Waltham, USA",
    experience: "6+ years",
  },
  {
    title: "Game Tester",
    company: "Ubisoft",
    location: "Montreal, Canada",
    experience: "2+ years",
  },
  {
    title: "Video Producer",
    company: "YouTube",
    location: "Los Angeles, USA",
    experience: "4+ years",
  },
  {
    title: "Social Media Manager",
    company: "TikTok",
    location: "Beijing, China",
    experience: "3+ years",
  },
  {
    title: "Automotive Engineer",
    company: "Ferrari",
    location: "Maranello, Italy",
    experience: "6+ years",
  },
  {
    title: "VR Developer",
    company: "Oculus",
    location: "California, USA",
    experience: "4+ years",
  },
  {
    title: "Bioinformatics Scientist",
    company: "23andMe",
    location: "Palo Alto, USA",
    experience: "5+ years",
  },
  {
    title: "Software Engineer",
    company: "Google",
    location: "California, USA",
    experience: "2+ years",
  },
  {
    title: "Cloud Engineer",
    company: "IBM",
    location: "Toronto, Canada",
    experience: "2+ years",
  },
  {
    title: "Frontend Developer",
    company: "TCS",
    location: "Mumbai, India",
    experience: "3+ years",
  },
  {
    title: "Backend Developer",
    company: "Infosys",
    location: "Bangalore, India",
    experience: "2+ years",
  },
  {
    title: "Data Scientist",
    company: "Wipro",
    location: "Pune, India",
    experience: "4+ years",
  },
  {
    title: "Machine Learning Engineer",
    company: "HCL Technologies",
    location: "Noida, India",
    experience: "3+ years",
  },
  {
    title: "DevOps Engineer",
    company: "Tech Mahindra",
    location: "Hyderabad, India",
    experience: "5+ years",
  },
  {
    title: "Cyber Security Analyst",
    company: "Capgemini",
    location: "Chennai, India",
    experience: "2+ years",
  },
  {
    title: "System Administrator",
    company: "Mindtree",
    location: "Bangalore, India",
    experience: "3+ years",
  },
  {
    title: "AI Engineer",
    company: "L&T Infotech",
    location: "Mumbai, India",
    experience: "4+ years",
  },
  {
    title: "Full Stack Developer",
    company: "Mphasis",
    location: "Pune, India",
    experience: "3+ years",
  },
  {
    title: "Cloud Architect",
    company: "Zensar Technologies",
    location: "Hyderabad, India",
    experience: "6+ years",
  },
  {
    title: "Software Tester",
    company: "Persistent Systems",
    location: "Nagpur, India",
    experience: "2+ years",
  },
  {
    title: "Embedded Systems Engineer",
    company: "KPIT Technologies",
    location: "Pune, India",
    experience: "4+ years",
  },
  {
    title: "Product Manager",
    company: "Cognizant",
    location: "Chennai, India",
    experience: "5+ years",
  },
  {
    title: "Data Engineer",
    company: "Oracle India",
    location: "Bangalore, India",
    experience: "3+ years",
  },
  {
    title: "IT Support Engineer",
    company: "Harman India",
    location: "Delhi, India",
    experience: "2+ years",
  },
  {
    title: "Network Engineer",
    company: "Red Hat India",
    location: "Pune, India",
    experience: "4+ years",
  },
  {
    title: "Software Developer",
    company: "Barclays",
    location: "London, UK",
    experience: "3+ years",
  },
  {
    title: "Cloud Engineer",
    company: "HSBC",
    location: "London, UK",
    experience: "5+ years",
  },
  {
    title: "Data Analyst",
    company: "Lloyds Bank",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "Security Engineer",
    company: "Revolut",
    location: "London, UK",
    experience: "3+ years",
  },
  {
    title: "Java Developer",
    company: "BT Group",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "IT Consultant",
    company: "Accenture UK",
    location: "London, UK",
    experience: "5+ years",
  },
  {
    title: "Full Stack Developer",
    company: "Deloitte UK",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "Business Analyst",
    company: "EY UK",
    location: "London, UK",
    experience: "3+ years",
  },
  {
    title: "Technical Lead",
    company: "PwC UK",
    location: "London, UK",
    experience: "6+ years",
  },
  {
    title: "Software Engineer",
    company: "Amazon UK",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "Frontend Developer",
    company: "Google UK",
    location: "London, UK",
    experience: "3+ years",
  },
  {
    title: "DevOps Engineer",
    company: "Microsoft UK",
    location: "London, UK",
    experience: "5+ years",
  },
  {
    title: "AI Researcher",
    company: "DeepMind",
    location: "London, UK",
    experience: "6+ years",
  },
  {
    title: "Data Engineer",
    company: "Spotify UK",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "QA Engineer",
    company: "Facebook UK",
    location: "London, UK",
    experience: "3+ years",
  },
  {
    title: "Cyber Security Analyst",
    company: "KPMG UK",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "Machine Learning Engineer",
    company: "Apple UK",
    location: "London, UK",
    experience: "5+ years",
  },
  {
    title: "Blockchain Developer",
    company: "IBM UK",
    location: "London, UK",
    experience: "4+ years",
  },
  {
    title: "Game Developer",
    company: "Rockstar Games",
    location: "London, UK",
    experience: "3+ years",
  },
  {
    title: "IT Project Manager",
    company: "Tesco",
    location: "London, UK",
    experience: "6+ years",
  },
  {
    title: "Software Engineer",
    company: "Google",
    location: "California, USA",
    experience: "Fresher",
  },
  {
    title: "Cloud Engineer",
    company: "IBM",
    location: "Toronto, Canada",
    experience: "1+ years",
  },
  {
    title: "Frontend Developer",
    company: "TCS",
    location: "Mumbai, India",
    experience: "Fresher",
  },
  {
    title: "Backend Developer",
    company: "Infosys",
    location: "Bangalore, India",
    experience: "1+ years",
  },
  {
    title: "Data Scientist",
    company: "Wipro",
    location: "Pune, India",
    experience: "1+ years",
  },
  {
    title: "Machine Learning Engineer",
    company: "HCL Technologies",
    location: "Noida, India",
    experience: "Fresher",
  },
  {
    title: "DevOps Engineer",
    company: "Tech Mahindra",
    location: "Hyderabad, India",
    experience: "1+ years",
  },
  {
    title: "Cyber Security Analyst",
    company: "Capgemini",
    location: "Chennai, India",
    experience: "Fresher",
  },
  {
    title: "System Administrator",
    company: "Mindtree",
    location: "Bangalore, India",
    experience: "1+ years",
  },
  {
    title: "AI Engineer",
    company: "L&T Infotech",
    location: "Mumbai, India",
    experience: "Fresher",
  },
  {
    title: "Software Engineer",
    company: "Accenture",
    location: "London, UK",
    experience: "1+ years",
  },
  {
    title: "Cloud Architect",
    company: "Cognizant",
    location: "Berlin, Germany",
    experience: "Fresher",
  },
  {
    title: "Full Stack Developer",
    company: "Atos",
    location: "Munich, Germany",
    experience: "1+ years",
  },
  {
    title: "Software Tester",
    company: "DXC Technology",
    location: "Sydney, Australia",
    experience: "Fresher",
  },
  {
    title: "Big Data Engineer",
    company: "SAP",
    location: "Walldorf, Germany",
    experience: "1+ years",
  },
  {
    title: "Network Engineer",
    company: "Fujitsu",
    location: "London, UK",
    experience: "Fresher",
  },
  {
    title: "Cybersecurity Specialist",
    company: "KPMG",
    location: "Melbourne, Australia",
    experience: "1+ years",
  },
  {
    title: "Backend Developer",
    company: "Deloitte Digital",
    location: "Sydney, Australia",
    experience: "Fresher",
  },
  {
    title: "Frontend Engineer",
    company: "EY",
    location: "London, UK",
    experience: "1+ years",
  },
  {
    title: "AI Researcher",
    company: "Siemens",
    location: "Berlin, Germany",
    experience: "Fresher",
  },
  {
    title: "IT Consultant",
    company: "PwC",
    location: "Manchester, UK",
    experience: "1+ years",
  },
  {
    title: "DevOps Engineer",
    company: "Infosys",
    location: "Sydney, Australia",
    experience: "Fresher",
  },
  {
    title: "Software Developer",
    company: "Nagarro",
    location: "Berlin, Germany",
    experience: "1+ years",
  },
  {
    title: "Cloud Engineer",
    company: "Tata Consultancy Services",
    location: "Melbourne, Australia",
    experience: "Fresher",
  },
  {
    title: "Embedded Systems Engineer",
    company: "Bosch",
    location: "Stuttgart, Germany",
    experience: "1+ years",
  },
  {
    title: "Blockchain Developer",
    company: "Hewlett Packard Enterprise",
    location: "London, UK",
    experience: "Fresher",
  },
  {
    title: "Software Architect",
    company: "Google UK",
    location: "London, UK",
    experience: "1+ years",
  },
  {
    title: "IT Project Manager",
    company: "IBM Germany",
    location: "Frankfurt, Germany",
    experience: "Fresher",
  },
  {
    title: "Security Engineer",
    company: "Amazon Web Services",
    location: "Sydney, Australia",
    experience: "1+ years",
  },
];
export default jobs;
