const test = [
  {
    id: 1,
    name: "John Doe",
    designation: "CEO, TechCorp",
    testimonial:
      "This product has transformed the way we work. Exceptional quality and outstanding support!",
    rating: 5,
  },
  {
    id: 2,
    name: "Jane Smith",
    designation: "Marketing Manager, Brandify",
    testimonial:
      "I love how intuitive and easy to use it is. Highly recommend it to anyone!",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Robert Johnson",
    designation: "Product Manager, InnovateX",
    testimonial:
      "A game-changer for our team. Increased efficiency and smoother collaboration.",
    rating: 5,
  },
  {
    id: 4,
    name: "Emily Davis",
    designation: "Founder, StartUpPro",
    testimonial:
      "Excellent service and super responsive team. Delighted with the results!",
    rating: 4.8,
  },
  {
    id: 5,
    name: "Michael Brown",
    designation: "CTO, FutureTech",
    testimonial:
      "Revolutionized our processes. Couldn't be happier with the outcome.",
    rating: 5,
  },
  {
    id: 6,
    name: "Sophia Wilson",
    designation: "Head of Operations, MoveFast",
    testimonial: "User-friendly and robust. Exactly what we needed.",
    rating: 4.7,
  },
  {
    id: 7,
    name: "William Taylor",
    designation: "Director, BuildIt",
    testimonial: "I am impressed by the performance and customer support.",
    rating: 4.9,
  },
  {
    id: 8,
    name: "Olivia Martinez",
    designation: "VP, GrowthPulse",
    testimonial: "Highly satisfied with the seamless experience provided.",
    rating: 4.6,
  },
  {
    id: 9,
    name: "James Anderson",
    designation: "Software Engineer, CodeWorks",
    testimonial:
      "The best tool we've adopted this year—saves us hours of work.",
    rating: 5,
  },
  {
    id: 10,
    name: "Ava Garcia",
    designation: "Project Lead, NextGen",
    testimonial: "Reliable, efficient, and worth every penny.",
    rating: 4.8,
  },
  {
    id: 11,
    name: "Benjamin White",
    designation: "Creative Director, Visionary",
    testimonial: "Simple, elegant, and powerful. Our team loves it.",
    rating: 4.9,
  },
  {
    id: 12,
    name: "Mia Harris",
    designation: "Product Designer, Designify",
    testimonial: "A brilliant solution that fits perfectly into our workflow.",
    rating: 4.7,
  },
  {
    id: 13,
    name: "Ethan Clark",
    designation: "Manager, FastTrack",
    testimonial: "Highly adaptable and incredibly efficient.",
    rating: 4.6,
  },
  {
    id: 14,
    name: "Isabella Lewis",
    designation: "Data Analyst, Insightful",
    testimonial: "Saved us so much time and effort. Truly a life-saver.",
    rating: 5,
  },
  {
    id: 15,
    name: "Lucas Walker",
    designation: "Engineer, InnovateNow",
    testimonial: "A must-have for modern teams seeking efficiency.",
    rating: 4.8,
  },
  {
    id: 16,
    name: "Charlotte Hall",
    designation: "HR Manager, PeopleFirst",
    testimonial: "The ease of use is unmatched. I can't recommend it enough.",
    rating: 4.9,
  },
  {
    id: 17,
    name: "Daniel Allen",
    designation: "Consultant, BrightFuture",
    testimonial: "Innovative, powerful, and reliable—everything we wanted.",
    rating: 5,
  },
  {
    id: 18,
    name: "Amelia Scott",
    designation: "Marketing Specialist, BrandBoost",
    testimonial: "A fantastic tool that has streamlined our campaigns.",
    rating: 4.7,
  },
  {
    id: 19,
    name: "Henry Adams",
    designation: "CEO, QuickLaunch",
    testimonial: "An indispensable asset for our growth journey.",
    rating: 4.8,
  },
  {
    id: 20,
    name: "Grace Evans",
    designation: "Operations Lead, AgileFlow",
    testimonial: "Effortless integration and outstanding results.",
    rating: 5,
  },
  {
    id: 21,
    name: "Amit Kumar",
    designation: "CEO, TechIndia",
    testimonial:
      "This platform has optimized our operations beyond expectations.",
    rating: 5,
  },
  {
    id: 22,
    name: "Priya Sharma",
    designation: "Marketing Head, BrandWave",
    testimonial: "An invaluable tool that simplifies our workflow greatly.",
    rating: 4.7,
  },
  {
    id: 23,
    name: "Ravi Verma",
    designation: "CTO, FutureEdge",
    testimonial: "Reliable and efficient – a perfect fit for our team.",
    rating: 4.8,
  },
  {
    id: 24,
    name: "Neha Gupta",
    designation: "Product Manager, InnoVision",
    testimonial: "It has significantly boosted our productivity levels.",
    rating: 5,
  },
  {
    id: 25,
    name: "Arjun Mehta",
    designation: "Operations Lead, QuickSolve",
    testimonial: "Highly intuitive and meets all our business needs.",
    rating: 4.9,
  },
  {
    id: 26,
    name: "Divya Iyer",
    designation: "Head of Design, PixelPerfect",
    testimonial: "A sleek and user-friendly solution – we love it!",
    rating: 4.8,
  },
  {
    id: 27,
    name: "Rajesh Nair",
    designation: "Manager, CloudSync",
    testimonial: "Incredible efficiency and top-notch customer service.",
    rating: 4.9,
  },
  {
    id: 28,
    name: "Sneha Rao",
    designation: "VP, DataSphere",
    testimonial: "A must-have tool for modern businesses.",
    rating: 4.8,
  },
  {
    id: 29,
    name: "John Doe",
    designation: "CEO, TechCorp",
    testimonial:
      "This product has transformed the way we work. Exceptional quality and outstanding support!",
    rating: 5,
  },
  {
    id: 30,
    name: "Jane Smith",
    designation: "Marketing Manager, Brandify",
    testimonial:
      "I love how intuitive and easy to use it is. Highly recommend it to anyone!",
    rating: 4.5,
  },
  {
    id: 31,
    name: "Robert Johnson",
    designation: "Product Manager, InnovateX",
    testimonial:
      "A game-changer for our team. Increased efficiency and smoother collaboration.",
    rating: 5,
  },
  {
    id: 32,
    name: "Emily Davis",
    designation: "Founder, StartUpPro",
    testimonial:
      "Excellent service and super responsive team. Delighted with the results!",
    rating: 4.8,
  },
  {
    id: 33,
    name: "Michael Brown",
    designation: "CTO, FutureTech",
    testimonial:
      "Revolutionized our processes. Couldn't be happier with the outcome.",
    rating: 5,
  },
  {
    id: 34,
    name: "Sophia Wilson",
    designation: "Head of Operations, MoveFast",
    testimonial: "User-friendly and robust. Exactly what we needed.",
    rating: 4.7,
  },
  {
    id: 34,
    name: "William Taylor",
    designation: "Director, BuildIt",
    testimonial: "I am impressed by the performance and customer support.",
    rating: 4.9,
  },
  {
    id: 36,
    name: "Olivia Martinez",
    designation: "VP, GrowthPulse",
    testimonial: "Highly satisfied with the seamless experience provided.",
    rating: 4.6,
  },
  {
    id: 37,
    name: "James Anderson",
    designation: "Software Engineer, CodeWorks",
    testimonial:
      "The best tool we've adopted this year—saves us hours of work.",
    rating: 5,
  },
  {
    id: 38,
    name: "Ava Garcia",
    designation: "Project Lead, NextGen",
    testimonial: "Reliable, efficient, and worth every penny.",
    rating: 4.8,
  },
  {
    id: 39,
    name: "Noah Bennett",
    designation: "Project Manager, BuildBright",
    testimonial: "An essential tool for our daily operations. Love it!",
    rating: 4.9,
  },
  {
    id: 40,
    name: "Liam Parker",
    designation: "Engineer, TechFlow",
    testimonial: "Smooth integration and fantastic user experience.",
    rating: 4.8,
  },
  {
    id: 41,
    name: "Zoe Patel",
    designation: "Data Scientist, AnalyzeAI",
    testimonial: "Unmatched accuracy and efficiency—truly impressive.",
    rating: 5,
  },
  {
    id: 42,
    name: "Jack Wilson",
    designation: "Operations Lead, FastLane",
    testimonial: "A smart solution that has boosted our productivity.",
    rating: 4.7,
  },
  {
    id: 43,
    name: "Harper Lee",
    designation: "CEO, InnovateTech",
    testimonial: "A must-have product for modern businesses.",
    rating: 5,
  },
  {
    id: 44,
    name: "Evelyn Scott",
    designation: "HR Director, PeopleCare",
    testimonial: "Simplified our processes and improved collaboration.",
    rating: 4.8,
  },
  {
    id: 45,
    name: "Mason Clark",
    designation: "Product Manager, VisionaryTech",
    testimonial: "Innovative and user-friendly—a powerful combination.",
    rating: 5,
  },
  {
    id: 46,
    name: "Ella Adams",
    designation: "CTO, BrightFuture",
    testimonial: "Game-changing technology with excellent support.",
    rating: 4.9,
  },
  {
    id: 47,
    name: "Logan Evans",
    designation: "Marketing Lead, BrandEdge",
    testimonial: "Exceeded our expectations in every way.",
    rating: 4.7,
  },
  {
    id: 48,
    name: "Aiden King",
    designation: "Developer, CodeSprint",
    testimonial: "An indispensable tool for our development team.",
    rating: 4.8,
  },
  {
    id: 49,
    name: "Scarlett Nguyen",
    designation: "Founder, StartSmart",
    testimonial: "Smart, efficient, and easy to use—perfect for startups.",
    rating: 5,
  },
  {
    id: 50,
    name: "Daniel Green",
    designation: "Head of Analytics, DataDriven",
    testimonial: "Powerful analytics with a seamless user experience.",
    rating: 4.9,
  },
  {
    id: 51,
    name: "Chloe White",
    designation: "Product Designer, CreateHub",
    testimonial: "Beautiful design and intuitive functionality.",
    rating: 4.8,
  },
  {
    id: 52,
    name: "Oliver Black",
    designation: "Operations Manager, SpeedyOps",
    testimonial: "A time-saving solution that we can't live without.",
    rating: 5,
  },
  {
    id: 53,
    name: "Mila Carter",
    designation: "VP, BrightVision",
    testimonial: "Exceptional service and top-tier performance.",
    rating: 4.8,
  }
];

export default test;
